#!/bin/bash
set -eo pipefail

eval "$(conda shell.bash hook)"

conda activate kernel
# ^ the env that actually contains the interpreter defined in `runtime.txt`
pipenv install --system
# install dependencies from Pipfile
